### ISSUE TITLE
Separate Ona Collect and ODK Collect directories

### ISSUE THREAD

**Issue by rowo** [onaio/collect#30]

**Comment by jmunene** [comment]
@rowo 
- GeoODK creates its own folder **geoodk** So when I download forms from Ona using it, I dont get the prompt to choose which application to use while filling in  a new form.
- KoboCollect creates a folder called **odk** and if installed alongside ODK Collect and Ona Collect, when filling in a new form, you're prompted to use ODK, Kobo or Ona.
- EarlySail ODK wasn't able to install on my phone, was getting a 505 error though on their details they've mentioned it can run side by side with any ODK collect/app
- KLL Collect wasn't able to install on my phone, was getting a 505 error though on their details they've mentioned its a clone of GeoODK, will try later
  SurveyCTO creates their own folder **SurveyCTO**

**Comment by mberg** [comment]
Think we need to create our own folder.  Jonathan can you create an issue.
We might need to have Koros patch ona collect 1.2 for us and we can
announce this in a patch release

**Comment by jasonrogena** [comment]
Here are some consequences of changing the directory:
 - Apps that read from or write to the `/sdcard/odk` directory will not work well with Ona Collect. STEPS, and OMK are some examples
 - Since Ona Collect now writes to another directory, we'll also need to change the shared intent for filling a blank form (so that ODK Collect is not shown as an alternative for filling forms--since it will write the responses in `/sdcard/odk`). Changing the shared intent will mean that apps that call the ODK Collect fill blank form intent will not work with Ona Collect

**Comment by rowo** [comment]
@mberg we are not changing the folder for now. For reasons, check with Jason and Dickson, but what I understood is it would be less support needs and there was no super strong reason to separate them at this point.
